drink = "tea" # Initialize the drink variable (string)
sales = {"tea": 3, "coffee": 5} # Initialize the sales dictionary (dictionary)
sold = sales[drink] # Get the number of sold items for the specified drink (integer)
sold = sold + 1 # Increment the sold count (integer)
print(drink) # Print the drink name (string)
print(sold) # Print the updated sold count (integer)
